### ISSUE TITLE
완전 매핑 전략 적용

### ISSUE THREAD

**Issue by Srltas** [f-lab-edu/run-together#30]
## 📋 Description
현재 `NeighborhoodVerificationService`는 웹 어댑터(Web Adapter)에서 사용하는 DTO를 파라미터로 받아 그래도 사용하고 있습니다. 이로 인해, 계층 간 경계가 불명확해지고, 비즈니스 로직과 어댑터의 의존성이 높아지는 문제가 발생합니다.

이를 개선하기 위해, 각 유즈케이스에 특화된 Command 객체를 정의하고, 이 객체를 서비스의 입력 모델로 사용하는 방식을 도입하고자 합니다.
Command 객체는 각 유즈케이스의 요구 사항에 맞는 전용 필드와 유효성 검증 로직을 포함하며, 이러한 설계를 통해 계층 간 경계를 명확하게 하고, 코드의 일관성과 유지보수성을 높일 수 있습니다.

이러한 변경을 통해 서비스 계층에서 웹 어댑터의 DTO 대신 Command 객체를 사용하여 로직을 처리하고, 어댑터 계층은 Command 객체로의 변환을 책임지게 합니다. 이를 통해 각 계층의 역할을 명확히 분리하고, 결합도를 낮추며, 보다 유연한 설계를 할 수 있다고 생각합니다. 

## ✅ Todo
- [x] 동네 인증 전용 Command 생성
- [x] 웹 어댑터 DTO와 Command를 변경할 Mapper 생성
- [x] 동네 인증 유즈케이스 인터페이스 생성
- [x] 동네 인증 서비스 수정

## 📚 References
[만들면서 배우는 클린 아키텍처, 톰 홈버그, 위키북스, 2021](https://product.kyobobook.co.kr/detail/S000001766486)
