### ISSUE TITLE
동네 등록 서비스 구현

### ISSUE THREAD

**Issue by Srltas** [f-lab-edu/run-together#32]
## 📋 Description
사용자는 러닝 모임을 검색하기 위해 동네를 등록해야 합니다. 사용자는 최대 2개의 동네만 등록할 수 있으며, 이를 통해 특정 동네에 있는 러닝 모임을 찾고 참여할 수 있습니다.

## ✅ Todo
- [x] 사용자가 등록하고자 하는 동네를 선택하면 새로운 동네를 등록할 수 있도록 기능 구현
- [x] 최대 2개의 동네를 등록할 수 있도록 제한하는 로직 추가
- [x] 이미 2개를 등록한 사용자가 추가 동네를 등록하려고 할 경우, 오류 메시지 반환
