### ISSUE TITLE
사용자 세션 관리 및 인증 토큰 기반 사용자 정보 주입 기능

### ISSUE THREAD

**Issue by Srltas** [f-lab-edu/run-together#35]
## 📋 Description
사용자 세션을 통한 인증 기능을 추가하고자 합니다. 사용자는 로그인 과정을 통해 인증을 받고, 사용자에게 발급된 토큰을 통해 인증된 사용자 정보가 매 요청마다 컨트롤러에 주입되도록 기능을 설계합니다. 이 기능은 모든 요청마다 사용자 토큰을 확인하여, 해당 토큰에 매핑된 사용자 정보를 컨트롤러에 전달하는 방식으로 구현됩니다.

## ✅ Todo
- [x] 로그인 한 사용자를 검증하는 filter 생성
- [x] 요청 Header의 Authorization에서 Bearer 토큰으로 SessionID를 저장
- [x] Filter에서 SessionID를 가지고 SessionStorage를 통해 사용자 확인
- [x] HttpSession에 "USER_SESSION"의 key 값으로 사용자 정보를 저장
- [x] Controller에서는  HttpSession에서 사용자 정보 확인 및 사용

## 📚 References
N/A
