### ISSUE TITLE
MyBatis와 MySQL 연동을 위한 설정 작업

### ISSUE THREAD

**Issue by Srltas** [f-lab-edu/run-together#44]
## 📋 Description
이번 프로젝트에서는 데이터베이스 연동을 위해 MyBatis와 MySQL을 사용하기로 결정했습니다.
이에 따라 MySQL, MyBatis 관련 설정 작업을 하고자 합니다.

## ✅ Todo
- [x] Gradle 의존성 추가
- [x] application.yml 설정 추가
- [x] db 설정파일 추가 및 .gitignore 설정
