### ISSUE TITLE
동네 인증 기능에 대한 영속성 어댑터 구현

### ISSUE THREAD

**Issue by Srltas** [f-lab-edu/run-together#46]
## 📋 Description
MyBatis를 이용해 동네 인증 기능에 대해 영속성 어댑터를 구현합니다.

## ✅ Todo
- [x] 영속성 포트 인터페이스 구현
- [x] MyBatis 영속성 어댑터 구현
- [x] 애플리케이션 계층과 영속성 계층 사이에서 사용할 DAO 구현

## 📚 References
[톰 홈버그, 2021, 만들면서 배우는 클린 아키텍처, 위키북스](https://product.kyobobook.co.kr/detail/S000001766486)
