### ISSUE TITLE
내 동네 등록 기능 영속성 어댑터 구현

### ISSUE THREAD

**Issue by Srltas** [f-lab-edu/run-together#52]
## 📋 Description
내 동네 기능에 대한 영속성 어댑터를 구현합니다.

## ✅ Todo
- [x] 유저와 내 동네 등록에 대한 애그리거트 정리
- [x] 내 동네 등록 Repository, Mapper 구현
- [x] 내 동네 등록 기능에 대한 테스트 코드 작성

## 📚 References
[최범균, 2022, 도메인 주도 개발 시작하기](https://product.kyobobook.co.kr/detail/S000001810495)
