### ISSUE TITLE
공통된 Exception 처리 및 에러 코드 구현

### ISSUE THREAD

**Issue by Srltas** [f-lab-edu/run-together#55]
## 📋 Description
현재 프로젝트에서 발생할 수 있는 다양한 예외 상황을 일관된 방식으로 처리하고, 에러 코드를 통해 명확하게 구분하고자 합니다. 이를 위해 @ControllerAdice를 사용하여 공동퇸 예외 처리 핸들러를 구현하고, 예외를 체계적으로 구조화하여 관리할 계획입니다.

**주요 목표**
1. 공통 예외 처리 핸들러 구성
   - @RestControllerAdvice를 활용하여 모든 예외를 통합적으로 처리하는 전역 예외 처리 핸들러를 만듭니다.
2. 예외 구조화
   - 프로젝트에서 발생할 수 있는 모든 예외는 모두 `RunTogetherException`을 상속하여 관리하며, 예외 성격에 따라 추가적인 예외 계층을 설계합니다.
   - DB 데이터 조회 실패, API에 대한 권한이 없어 실패하는 경우 발생하는 예외는 별도의 상속 계층을 구성합니다.
3. 에러 코드 부여
   - 각 예외 상황에 고유한 에러 코드를 부여하여 enum으로 관리하고, 이를 예외 처리 핸들러에서 사용해 예외 상황별 에러 코드를 포함하여 응답할 수 있도록 구성합니다.
4. 표준화된 예외 응답 형식 제공
   - ErrorResponse 클래스를 정의하여, 일관된 에러 응답 형식을 반환할 수 있도록 합니다.

## ✅ Todo
- [x] 전역 예외 처리 핸들러 생성
- [x] 예외 구조화
- [x] 에러 코드 부여
- [x] 표준화 된 응답 형식

## 📚 References
[Kakao Developers](https://developers.kakao.com/docs/latest/ko/rest-api/reference#error-code)
[Exception 전략 블로그 글 1](https://cheese10yun.github.io/spring-guide-exception/#null)
[Exception 전략 블로그 글 2](https://jaehoney.tistory.com/275)
