### ISSUE TITLE
Logger 적용

### ISSUE THREAD

**Issue by Srltas** [f-lab-edu/run-together#59]
## 📋 Description
프로젝트에서 Log4j2를 사용해 로그 관리를 하고자 합니다.

처음 어떤 로그 라이브러리를 선택해야 하나 고민 했을 때 Logback을 사용하는 것은 어떤지 고민 했습니다.
Logback을 고민한 이유는 Logback은 초당 약 1,760,000개의 로그 이벤트를 처리할 수 있는 성능[(Logback 공식 성능 벤치마크)](https://logback.qos.ch/performance.html)을 갖추고 있고, 기본적으로 Spring Boot에서 제공되어 별도의 설정 없이도 초기 단계에서 성능과 요구사항을 충족할 수 있는 적절한 선택이었습니다.

하지만, Log4j2는 Logback의 아키텍처적 한계를 개선하여 멀티스레드 환경에서 18배 높은 성능[(Log4j2 공식 문서)](https://logging.apache.org/log4j/2.12.x/)과 설정 파일을 다양한 형식으로 작성할 수 있는 유연함을 제공합니다. 추가 설정이 필요하긴 하지만, Spring Boot와의 호환성이 좋기 때문에 설정 과정도 간단히 해결할 수 있습니다.

두 라이브러리 모두 사용에 큰 문제는 없으나, 성능과 유연성이 더 좋은 최신 버전의 로그 라이브러리인 Log4j2를 사용하는 것 더 유리하다 생각해 Log4j2로 결정했습니다.

## ✅ Todo
- [x] Log4j2 설정
- [x] 클라이언트 요청에 대한 로그를 기록할 Filter 생성
- [x] 클라이언트 요청에 대한 로그는 MDC를 활용하여 기록하고, 요청 로그는 별도의 access 로그 파일로 분리하여 관리합니다.
- [x] JSON 로그 포맷 형식으로 로그를 출력합니다.

**Comment by f-lab-bradley** [comment]
Log4j2 랑 비교해서 어떤게 더 좋은지 장단점을 작성 해 주세요

**Comment by Srltas** [comment]
> Log4j2 랑 비교해서 어떤게 더 좋은지 장단점을 작성 해 주세요

Log4j2와 비교해 이슈를 다시 작성해 봤습니다!
