### ISSUE TITLE
Redis Session 저장소 추가

### ISSUE THREAD

**Issue by Srltas** [f-lab-edu/run-together#61]
## 📋 Description
사용자 세션 관리를 위해 세션 저장소를 추가하려고 합니다. 세션 저장소는 Redis를 사용하기로 결정했습니다.
이를 통해 사용자 세션 정보를 Redis에 조회할 수 있는 코드를 추가합니다.

## ✅ Todo
- [x] `spring-boot-starter-data-redis`를 프로젝트에 추가
- [x] 사용자 세션 조회 코드 구현
- [x] 세션 데이터를 올바르게 조회하는지 테스트 코드 추가 또는 수정
