### ISSUE TITLE
배포 파이프라인 구축 

### ISSUE THREAD

**Issue by Srltas** [f-lab-edu/run-together#65]
## 📋 Description
자동화 된 배포 파이프라인을 구축합니다.

## ✅ Todo
- [ ] Naver Clould에 Docker 기반 배포 환경 설정
- [ ] GitHub Actions를 통한 CI/CD 파이프라인 구성
- [ ] main 브랜치 머지 시 유닛 테스트 및 자동 배포 설정
- [ ] 로컬 및 배포 환경별 설정 파일 분리 및 적용

## 📚 References
N/A
