### ISSUE TITLE
동네 조회 Repository 구현

### ISSUE THREAD

**Issue by Srltas** [f-lab-edu/run-together#66]
## 📋 Description
내 동네 등록, 내 동네 인증 기능에서 사용할 동네 조회 Repository를 구현합니다.

## ✅ Todo
- [x] Repository, Mapper 동네 조회 기능 추가
- [x] MyBatis XML 동네 조회 SQL 추가
- [x] 동네 조회 관련 DAO, Convertor 추가
