### ISSUE TITLE
러닝 그룹 생성 Repository 계층 구현

### ISSUE THREAD

**Issue by Srltas** [f-lab-edu/run-together#90]
## 📋 Description
러닝 그룹 생성 API에 대해 Repository 계층을 구현합니다.

## ✅ Todo
- [x] Group 도메인 생성
- [x] 러닝 그룹 추가 Repository, Mapper 생성
- [x] 러닝 그룹 추가 테스트 코드 작성
